[package]
name = "rlx"
version = "0.1.9"
edition = "2021"

[dependencies]
eyre = "0.6"
color-eyre = "0.6"
regex = "1.10"
clap = { version = "4.5",  features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { default-features = false, version = "1.25", features = ["full"] }
config = { version = "0.14", default-features = false, features = ["yaml"] }
url = { version = "2", features = ["serde"] }
colored = "2.1.0"
git2 = "0.13.14"
semver = "1.0.22"
