[package]
name = "rlx"
version = "0.1.8"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5",  features = ["derive"] }
serde = { version = "1", features = ["derive"] }
tokio = { default-features = false, version = "1.25", features = ["full"] }
config = { version = "0.14", default-features = false, features = ["yaml"] }
url = { version = "2", features = ["serde"] }
package-json = "0.4.0"
